/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        terracotta: {
          400: '#ea580c',
          500: '#c2410c',
          600: '#9a3412',
          700: '#7c2d12',
        },
        amberGlow: '#d97706',
        warm: {
          50: '#ffffff',
          100: '#faf8f5',
          200: '#f5f0e8',
          300: '#e8e0d4',
          400: '#d6cdc0',
          500: '#a8a29e',
          600: '#78716c',
          700: '#57534e',
          800: '#44403c',
          900: '#292524',
          950: '#1c1917',
        },
        "tertiary-container": "#0d1c2d",
        "on-secondary-container": "#54647a",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container": "#eceef0",
        "on-error": "#ffffff",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed": "#131b2e",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        "on-primary-container": "#7c839b",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#0b1c30",
        "outline": "#76777d",
        "surface": "#f7f9fb",
        "error-container": "#ffdad6",
        "secondary": "#505f76",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c6c6cd",
        "on-tertiary-fixed": "#0d1c2d",
        "tertiary": "#000000",
        "on-background": "#191c1e",
        "on-tertiary-container": "#768599",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed": "#d4e4fa",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#39485a",
        "primary": "#000000",
        "background": "#f7f9fb",
        "surface-tint": "#565e74",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed-dim": "#b7c8e1",
        "secondary-container": "#d0e1fb",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-primary": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "tertiary-fixed-dim": "#b9c8de",
        "primary-container": "#131b2e",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-surface-variant": "#45464d",
        "surface-bright": "#f7f9fb",
        "primary-fixed-dim": "#bec6e0"
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        serif: ['"Instrument Serif"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        "editorial": ["Cormorant Garamond", "Georgia", "serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "label-pill": ["Plus Jakarta Sans", "sans-serif"]
      },
      animation: {
        'spin-slow': 'spin 18s linear infinite',
        'marquee': 'marquee 25s linear infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        }
      }
    },
  },
  plugins: [],
}
